# Use a lightweight Python image
FROM python:3.11-slim  
 
# Set the working directory inside the container
WORKDIR /app  
 
# Copy your app code into the container
COPY app.py .  

# Install any needed packages specified in requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy templates and static folders
COPY templates/ ./templates/
COPY static/ ./static/
EXPOSE 8000

# Run the app when the container starts
CMD ["python", "app.py"]

